name: Flutter Actions

on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
      - run: ls -R
      - uses: actions/upload-artifact@v2
        with:
          name: android
          path: |
            ./build/app/outputs/apk/release/app-release.apk
            ./build/app/outputs/bundle/release/app-release.aab
          retention-days: 1
      # for later use
      # - name: build web
      #   uses: erickzanardo/flutter-gh-pages@v3

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v1
  #     - run: flutter config --enable-windows-desktop
  #     - run: flutter build windows
  
  # build-mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: subosito/flutter-action@v1
  #   - run: flutter pub get
  #   - run: flutter test
  #   - run: flutter build ios --release --no-codesign

  release:
    needs: [ build-linux ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: android
          path: artifacts
          
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            /build/app/outputs/apk/release/*.apk
            **/*.exe
