name: Flutter Actions

on:
  push:
    branches: [ master ]

jobs:
  get-version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: gitversion
        uses: codacy/git-version@2.2.0
    outputs:
      version: ${{ steps.gitversion.outputs.version  }}

  # build-linux:
  #   needs: [ get-version ]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'
  #     - uses: subosito/flutter-action@v1
  #     - name: Update version in YAML
  #       run: sed -i 's/0.0.0+0/${{ needs.get-version.outputs.version }}+${{ github.run_number }}/g' pubspec.yaml
  #     - run: flutter build apk
  #     - run: flutter build appbundle
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: android
  #         path: |
  #           ./build/app/outputs/apk/release/app-release.apk
  #           ./build/app/outputs/bundle/release/app-release.aab
  #         retention-days: 1
      # for later use
      # - name: build web
      #   uses: erickzanardo/flutter-gh-pages@v3

  # build-windows:
  #   needs: [ get-version ]
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v1
  #     - run: flutter config --enable-windows-desktop
  #     - name: Update version in YAML
  #       run: sed -i 's/0.0.0+0/${{ needs.get-version.outputs.version }}+${{ github.run_number }}/g' pubspec.yaml
  #     - run: flutter build windows
  #     # - run: flutter pub run msix:create
  #     - name: 'Tar files'
  #       run: tar -cvf flutter_ci_cd_windows.tar build/windows/runner/release
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: windows
  #         path: |
  #           flutter_ci_cd_windows.tar
  #           ./build/windows/runner/release/
  #         retention-days: 1
  
  # build-mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: subosito/flutter-action@v1
  #   - run: flutter pub get
  #   - run: flutter test
  #   - run: flutter build ios --release --no-codesign

  release:
    needs: [ get-version ]
    runs-on: ubuntu-latest

    steps:
      - name: show version
        run: echo "Releasing ${{ needs.get-version.outputs.version }}"

      - uses: actions/download-artifact@v2
        with:
          path: artifacts

      - uses: ardalanamini/auto-changelog@v1.1.0
        id: change
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: 'perf,other,breaking'
      
      - name: show version
        run: echo "Changelog ${{ steps.change.outputs.changelog }}"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.get-version.outputs.version }}
          commit: ${{ github.sha }}
          body: ${{ steps.change.outputs.changelog }}
          prerelease: true
          # artifacts: artifacts/android/apk/release/app-release.apk,artifacts/android/bundle/release/app-release.aab,artifacts/windows/flutter_ci_cd_windows.tar
