name: Flutter Actions

on:
  push:
    branches: [ master ]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter test

  get-version:
    if: "contains(github.event.head_commit.message, '[release]')"
    needs: [ run-test ]
    name: Create version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: gitversion
        uses: codacy/git-version@2.2.0
    outputs:
      version: ${{ steps.gitversion.outputs.version  }}
      release-name: ${{ github.event.repository.name }}_${{ steps.gitversion.outputs.version }}+${{ github.run_number }}

  build-linux:
    needs: [ get-version ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - name: Update version in YAML
        run: sed -i 's/0.0.0+0/${{ needs.get-version.outputs.version }}+${{ github.run_number }}/g' pubspec.yaml
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v2
        with:
          name: android
          path: |
            ./build/app/outputs/apk/release/app-release.apk
            ./build/app/outputs/bundle/release/app-release.aab
          retention-days: 1
      # for later use
      # - name: build web
      #   uses: erickzanardo/flutter-gh-pages@v3

  build-windows:
    needs: [ get-version ]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter config --enable-windows-desktop
      - name: Update version in YAML
        run: sed -i 's/0.0.0+0/${{ needs.get-version.outputs.version }}+${{ github.run_number }}/g' pubspec.yaml
      - run: flutter build windows
      # - run: flutter pub run msix:create
      - name: 'Tar files'
        run: tar -cvf ${{ needs.get-version.outputs.release-name }}.tar build/windows/runner/release
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: |
            ${{ needs.get-version.outputs.release-name }}.tar
            ./build/windows/runner/release/
          retention-days: 1
  
  # build-mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: subosito/flutter-action@v1
  #   - run: flutter pub get
  #   - run: flutter test
  #   - run: flutter build ios --release --no-codesign

  release:
    needs: [ get-version, build-linux, build-windows ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show version
        run: echo "Releasing ${{ needs.get-version.outputs.version }}+${{ github.run_number }}"
      
      - name: Update version in YAML
        run: >
          sed -i 's/^version: .*$/version: ${{ needs.get-version.outputs.version }}+${{ github.run_number }}/g' pubspec.yaml

      - uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Generate Changelog
        uses: ardalanamini/auto-changelog@v1.1.0
        id: change
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: 'perf,other,breaking'

      - name: Create or update changelog.md
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: changelog.md
          contents: |
            \n
            ## ${{ needs.get-version.outputs.version }}+${{ github.run_number }}
            ${{ steps.change.outputs.changelog }}
          write-mode: append

      - run: mv artifacts/android/apk/release/app-release.apk artifacts/android/apk/release/${{ needs.get-version.outputs.release-name }}.apk
      - run: mv artifacts/android/bundle/release/app-release.aab artifacts/android/bundle/release/${{ needs.get-version.outputs.release-name }}.aab
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.get-version.outputs.version }}+${{ github.run_number }}
          commit: ${{ github.sha }}
          body: ${{ steps.change.outputs.changelog }}
          prerelease: true
          artifacts: artifacts/android/apk/release/${{ needs.get-version.outputs.release-name }}.apk,artifacts/android/bundle/release/${{ needs.get-version.outputs.release-name }}.aab,artifacts/windows/${{ needs.get-version.outputs.release-name }}.tar

      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Auto Released ${{ needs.get-version.outputs.version }}+${{ github.run_number }}
